[general]
lang="en-US"
startOnBoot=false
startPosition=1
showInTray=false
minimizeToTray=false
closeToTray=false

[database]
databasePath=""
backupDatabase=false
backupPath=""

[tasks]
minutesIncrement=15
showProjectAssociatedCategories=false
useLegacyTaskDialog=false

[tasksView]
todayAlwaysExpanded=false

[export]
exportPath=""
presetCount=0

[[presets]]
