[general]
lang="en-US"
startOnBoot=false
startPosition=1
showInTray=false
minimizeToTray=false
closeToTray=false

[database]
databasePath=""
backupDatabase=false
backupPath=""

[tasks]
minutesIncrement=15
showProjectAssociatedCategories=false
useLegacyTaskDialog=false
useReminders=false
useNotificationBanners=false
useTaskbarFlashing=false
reminderInterval=0
openTaskDialogOnReminderClick=false
selectDefaultAttributeGroup=false

[tasksView]
todayAlwaysExpanded=false

[export]
exportPath=""
closeExportDialogAfterExporting=false
presetCount=0

[[presets]]
