[general]
lang="en-US"
startOnBoot=false
startPosition=1
showInTray=false
minimizeToTray=false
closeToTray=false

[database]
databasePath=""
backupDatabase=false
backupPath=""

[tasks]
minutesIncrement=15
showProjectAssociatedCategories=false
useReminders=false
useNotificationBanners=false
useTaskbarFlashing=false
reminderInterval=0
openTaskDialogOnReminderClick=false

[tasksView]
todayAlwaysExpanded=false
taskViewColumns = [
	{column = "Project", order = 1},
	{column = "Category", order = 2},
	{column = "Duration", order = 3},
	{column = "Description", order = 4}
]

[export]
exportPath=""
closeExportDialogAfterExporting=false
presetCount=0

[[presets]]
