[general]
lang="en-US"
startOnBoot=false
startPosition=0
showInTray=false
minimizeToTray=false
closeToTray=false

[database]
databasePath=""
backupDatabase=false
backupPath=""
backupRetentionPeriod=-1
